excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://murquhart.github.io
name: Awesome
description: My awesome new site
author: Thestrian
avatar: http://www.gravatar.com/avatar/e11a297118562707a8831bf5605becfe?s=120&d=mm&r=g
ga_domain: 
ga_tracking_id: 